# support for encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# enable OLED Display
CONFIG_ZMK_DISPLAY=y

# enable RGB underglow
CONFIG_ZMK_RGB_UNDERGLOW=y
# no battery ststus
CONFIG_ZMK_WIDGET_BATTERY_STATUS=n
# longer timeout
CONFIG_ZMK_IDLE_TIMEOUT=300000
# default rgb conf
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=10
CONFIG_ZMK_RGB_UNDERGLOW_SPD_START=3
# spectrum
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=2
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y

ZMK_STUDIO=y
